/*
 * Employee Management
 * This is a camel-k demo for creating and updating an employee
 *
 * OpenAPI spec version: 1.0.0
 * Contact: david.borja@modusbox.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.modusbox.employee.auth;

import com.modusbox.employee.Pair;

import java.util.Map;
import java.util.List;

public interface Authentication {
    /**
     * Apply authentication settings to header and query params.
     *
     * @param queryParams List of query parameters
     * @param headerParams Map of header parameters
     */
    void applyToParams(List<Pair> queryParams, Map<String, String> headerParams);
}
